### ISSUE TITLE
Random S showing up just behind the login username

### ISSUE THREAD

**Issue by chrisjameschamp** [Kangie/sddm-sugar-candy#2]
I have had this issue on multiple Arch distros and I cannot seem to figure out how to solve it.  I did remove the Combobox from the Inputs.qml file and that resolved it, but ideally I would like to leave that there for quick changing of users.  I have attached an image for reference

Occuring on Archlabs Linux x86_64 with Kernel 5.17.8-arch1-1

![IMG_0307](https://user-images.githubusercontent.com/38870317/169176272-1611033a-9fc3-4bb2-a959-44ebfa59ef53.JPG)

**Comment by ghost** [comment]
Same - did you ever solve this?

**Comment by ghost** [comment]
Update for anyone looking in the future: this can be fixed by changing line 94 in Components/Input.qml. The horizontal margin defaults to a percentage of screen height:

https://github.com/Kangie/sddm-sugar-candy/blob/a1fae5159c8f7e44f0d8de124b14bae583edb5b8/Components/Input.qml#L94

Which presumably doesn't work for all resolutions. A margin of 0 didn't quite work for my display, but this looks perfect:

`anchors.leftMargin: -7`

Good luck!

**Comment by Kangie** [comment]
Fwiw this is fixed in my updated fork 'eucalyptus drop' available [here](https://gitlab.com/Matt.Jolly/sddm-eucalyptus-drop) or published to various 'stores'.

I'll try and backport these fixes for anyone subscribed here once I have time, but this repo mostly exists so that I had easy tags for ebuild writing. :)

**Comment by timoleistner** [comment]
The solution is inserting a line below line 47 `displayText: ""` (if you leave the copyright stuff on the original place at the top).
https://github.com/Kangie/sddm-sugar-candy/blob/a1fae5159c8f7e44f0d8de124b14bae583edb5b8/Components/Input.qml#L44-L48
```
ComboBox {

    id: selectUser

    displayText: ""
    width: parent.height
```
